version: 0.0
os: linux
files:
  - source: /flipbot
    destination: /home/arch/flipbot/
hooks:
  BeforeInstall:
    - location: remove.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: restart.sh
      timeout: 300
      runas: root
