version: 0.2

phases:
  install:
    commands:
      - go get -u golang.org/x/lint/golint

  pre_build:
    commands:
      - golint -set_exit_status
      - go vet
      - go test

  build:
    commands:
      - go build -o flipbot

artifacts:
  files:
    - flipbot
    - appspec.yml
    - restart.sh
